// Data Smartphone Low-End (1jt - 2.5jt)
const smartphoneData = [
  {
    id: 1,
    alternatif: "A1",
    nama: "Itel A90 (4/128GB)",
    harga: 1,
    ram: 4,
    memori: 128,
    kamera: 13,
    baterai: 5000,
    processor: "Unisoc T7100",
    cpuGhz: 1.8,
    nanometer: 28,
    charging: 15,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 2,
    alternatif: "A2",
    nama: "Tecno Spark Go 1 (4/64GB)",
    harga: 1.05,
    ram: 4,
    memori: 64,
    kamera: 13,
    baterai: 5000,
    processor: "Unisoc T615",
    cpuGhz: 1.8,
    nanometer: 12,
    charging: 15,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 3,
    alternatif: "A3",
    nama: "Infinix Smart 10 (4/128GB)",
    harga: 1.25,
    ram: 4,
    memori: 128,
    kamera: 8,
    baterai: 5000,
    processor: "Unisoc T7250",
    cpuGhz: 1.8,
    nanometer: 12,
    charging: 15,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 4,
    alternatif: "A4",
    nama: "Vivo Y03 (4/64GB)",
    harga: 1.3,
    ram: 4,
    memori: 64,
    kamera: 13,
    baterai: 5000,
    processor: "MediaTek Helio G85",
    cpuGhz: 2.0,
    nanometer: 12,
    charging: 15,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 5,
    alternatif: "A5",
    nama: "Realme Note 50 (4/128GB)",
    harga: 1.4,
    ram: 4,
    memori: 128,
    kamera: 13,
    baterai: 5000,
    processor: "Unisoc T612",
    cpuGhz: 1.8,
    nanometer: 12,
    charging: 10,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 6,
    alternatif: "A6",
    nama: "Xiaomi Redmi 14C (8/128GB)",
    harga: 1.7,
    ram: 8,
    memori: 128,
    kamera: 50,
    baterai: 5160,
    processor: "MediaTek Helio G81 Ultra",
    cpuGhz: 2.0,
    nanometer: 12,
    charging: 18,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 7,
    alternatif: "A7",
    nama: "Samsung Galaxy A07 (6/128GB)",
    harga: 1.95,
    ram: 6,
    memori: 128,
    kamera: 50,
    baterai: 5000,
    processor: "MediaTek Helio G99",
    cpuGhz: 2.2,
    nanometer: 6,
    charging: 25,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 8,
    alternatif: "A8",
    nama: "Infinix Hot 40 Pro (8/256GB)",
    harga: 2.1,
    ram: 8,
    memori: 256,
    kamera: 108,
    baterai: 5000,
    processor: "MediaTek Helio G99",
    cpuGhz: 2.2,
    nanometer: 6,
    charging: 33,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 9,
    alternatif: "A9",
    nama: "Tecno Spark 20 Pro (8/256GB)",
    harga: 2.5,
    ram: 8,
    memori: 256,
    kamera: 108,
    baterai: 5000,
    processor: "MediaTek Helio G99",
    cpuGhz: 2.2,
    nanometer: 6,
    charging: 33,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 10,
    alternatif: "A10",
    nama: "Poco C65 (6/128GB)",
    harga: 1.5,
    ram: 6,
    memori: 128,
    kamera: 50,
    baterai: 5000,
    processor: "MediaTek Helio G85",
    cpuGhz: 2.0,
    nanometer: 12,
    charging: 18,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 11,
    alternatif: "A11",
    nama: "Oppo A18 (4/128GB)",
    harga: 1.45,
    ram: 4,
    memori: 128,
    kamera: 13,
    baterai: 5000,
    processor: "MediaTek Helio G85",
    cpuGhz: 2.0,
    nanometer: 12,
    charging: 10,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 12,
    alternatif: "A12",
    nama: "Samsung Galaxy A05s (6/128GB)",
    harga: 2,
    ram: 6,
    memori: 128,
    kamera: 50,
    baterai: 5000,
    processor: "Qualcomm Snapdragon 680 4G",
    cpuGhz: 2.4,
    nanometer: 6,
    charging: 25,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 13,
    alternatif: "A13",
    nama: "Realme C65 (8/256GB)",
    harga: 2.4,
    ram: 8,
    memori: 256,
    kamera: 50,
    baterai: 5000,
    processor: "MediaTek Helio G85",
    cpuGhz: 2.0,
    nanometer: 12,
    charging: 45,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 14,
    alternatif: "A14",
    nama: "Vivo Y28 (8/256GB)",
    harga: 2.5,
    ram: 8,
    memori: 256,
    kamera: 50,
    baterai: 6000,
    processor: "MediaTek Helio G85",
    cpuGhz: 2.0,
    nanometer: 12,
    charging: 44,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 15,
    alternatif: "A15",
    nama: "Itel P70 (4/128GB)",
    harga: 1.35,
    ram: 4,
    memori: 128,
    kamera: 13,
    baterai: 6000,
    processor: "MediaTek Helio G50 Ultimate",
    cpuGhz: 2.2,
    nanometer: 12,
    charging: 18,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 16,
    alternatif: "A16",
    nama: "Xiaomi Redmi Note 13 (8/256GB)",
    harga: 2.05,
    ram: 8,
    memori: 256,
    kamera: 108,
    baterai: 5000,
    processor: "MediaTek Dimensity 6080",
    cpuGhz: 2.4,
    nanometer: 6,
    charging: 33,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 17,
    alternatif: "A17",
    nama: "Samsung Galaxy A15 (8/128GB)",
    harga: 2.7,
    ram: 8,
    memori: 128,
    kamera: 50,
    baterai: 5000,
    processor: "MediaTek Helio G99",
    cpuGhz: 2.2,
    nanometer: 6,
    charging: 25,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 18,
    alternatif: "A18",
    nama: "Tecno Pova 6 (8/256GB)",
    harga: 2.45,
    ram: 8,
    memori: 256,
    kamera: 108,
    baterai: 6000,
    processor: "MediaTek Helio G99 Ultimate",
    cpuGhz: 2.2,
    nanometer: 6,
    charging: 70,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 19,
    alternatif: "A19",
    nama: "Oppo A60 (8/128GB)",
    harga: 2.6,
    ram: 8,
    memori: 128,
    kamera: 50,
    baterai: 5000,
    processor: "Qualcomm Snapdragon 680 4G",
    cpuGhz: 2.4,
    nanometer: 6,
    charging: 45,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  },
  {
    id: 20,
    alternatif: "A20",
    nama: "Poco M7 Pro (8/256GB)",
    harga: 2.8,
    ram: 8,
    memori: 256,
    kamera: 50,
    baterai: 5000,
    processor: "MediaTek Dimensity 7025 Ultra",
    cpuGhz: 2.5,
    nanometer: 6,
    charging: 45,
    kategori: "Low-End",
    rangeHarga: "Rp 1jt - 2.5jt"
  }
];

// Kriteria dan tipe (benefit/cost)
const criteria = {
  harga: { name: "Harga", type: "cost", unit: "Jt Rp" },
  ram: { name: "RAM", type: "benefit", unit: "GB" },
  memori: { name: "Memori", type: "benefit", unit: "GB" },
  kamera: { name: "Kamera", type: "benefit", unit: "MP" },
  baterai: { name: "Baterai", type: "benefit", unit: "mAh" },
  cpuGhz: { name: "CPU Clock", type: "benefit", unit: "GHz" },
  nanometer: { name: "Process Node", type: "cost", unit: "nm" },
  charging: { name: "Charging", type: "benefit", unit: "W" }
};

// Bobot default (total harus 100%)
const defaultWeights = {
  harga: 0.25,      // 25%
  ram: 0.20,        // 20%
  memori: 0.15,     // 15%
  kamera: 0.12,     // 12%
  baterai: 0.12,    // 12%
  cpuGhz: 0.08,     // 8%
  nanometer: 0.05,  // 5%
  charging: 0.03    // 3%
};
